config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'blog', to: 'pages#blog'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: { minimum: 6, maximum: 100}
    validates :description, presence: true, length: { minimum: 10, maximum: 300}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
  
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]

    def show
    end
  
    def index
      @articles = Article.all
    end
  
    def new
      @article = Article.new
    end

    def edit
       
    end
  
    def create
      @article = Article.new(article_params)
      if @article.save
        flash[:notice] = "Article was created successfully."
        redirect_to @article
      else
        render 'new'
      end
    end

    def update
       if @article.update(article_params)
            flash[:notice] = "Article was updated successfully."
            redirect_to @article
       else
        render 'edit'
        end
    end

    def destroy
        @article.destroy
        redirect_to articles_path
    end

  private

  def set_article
  @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end

    def about
    end

    def blog
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors' %>
      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
      <div class="form-group row">
        <%= f.label :title, class: "col-2 col-form-label text-light" %>
        <div class="col-10">
          <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :description, class: "col-2 col-form-label text-light" %>
        <div class="col-10">
          <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
        </div>
      </div>

      <div class="form-group row justify-content-center">
        <%= f.submit class: "btn btn-outline-light btn-lg" %>
      </div>
      <% end %>
    </div>
    <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
  </div>
</div>

app/views/articles/edit.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">Edit article</h1>
    <%= render 'form' %>
  </div> 

app/views/articles/index.html.erb
<div id="page-content">
  <h1 class="text-center mt-4">Listing all articles</h1>

  <div class="container">
    <% @articles.each do |article| %>
      <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
          <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header font-italic">
              by Jmin
            </div>
            <div class="card-body">
              <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
              <p class="card-text"><%= truncate(article.description, length: 100) %></p>
              <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
              <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
              <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            </div>
            <div class="card-footer text-muted">
              <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
              edited <%= time_ago_in_words(article.updated_at) %> ago</small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    </div>
  </div> 

app/views/articles/new.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">Create a new article</h1>
    <%= render 'form' %>
  </div> 

app/views/articles/show.html.erb
<div id="page-content">
    <h2 class="text-center mt-4"><%= @article.title %></h2>
    <div class="container">
        <div class="row justify-content-md-center">
          <div class="col-8 mt-4">
            <div class="card text-center shadow mb-5 bg-white rounded">
              <div class="card-header font-italic">
                by Jmin
              </div>
              <div class="card-body">
                <div class="card-text text-left"><%= simple_format(@article.description) %></div>
                <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
                <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
              </div>
              <div class="card-footer text-muted">
                <small>Created <%= time_ago_in_words(@article.created_at) %> ago, 
                edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div> 

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
    <div class="container text-center">
      <small>Copyright &copy; <%= link_to  "Double O", "https://doubleothreads.com", class: "text-white" %></small>
    </div>
  </footer>

app/views/layouts/_messages.html.erb
<div class="container">
<% flash.each do |name, msg| %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <%= msg %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to  "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Articles
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
              <%= link_to "View articles", articles_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is my about page</h1>

app/views/pages/blog.html.erb
<h1>This is my blog page</h1>

app/views/pages/home.html.erb
<div id="page-content">
  <div class="container" id="home-container">
    <div class="jumbotron text-center text-white">
      <h1 class="display-4">Alpha Blog</h1>
      <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
      <hr class="my-4">
      <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
      <a class="btn btn-success btn-lg" href="#" role="button">Sign up!</a>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if @article.errors.any? %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the article from being saved</h4>
    <ul>
        <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
</div>
<% end %>